GDS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('productos.urls')),
    path("select2/", include("django_select2.urls"))
]

productos/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.main, name='main'),
    path('producto/registrar', views.crearproducto, name='crearproducto'),
    path('categoria/registrar', views.crearcategoria, name='crearcategoria'),
    path('producto/compra/', views.crearcompra, name='compra'),
    path('producto/listar/', views.listar_producto, name='listarproducto'),
    path('categoria/listar/', views.listar_categoria, name='listarcategoria'),
    path('categoria/listar/eliminado/<int:categoria_id>', views.eliminar_categoria, name='eliminarcategoria'),
    path('producto/listar/eliminado/<int:producto_id>', views.eliminar_producto, name='eliminarproducto')
]

productos/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

class Categoria(models.Model):
    nombre = models.CharField(max_length=15, null=True, blank=True)
    descripcion = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.nombre

class Producto(models.Model):
    nombre = models.CharField(max_length=15, null=False)
    descripcion = models.TextField(blank=True, null=True)
    stock_actual = models.PositiveIntegerField(default=0)
    stock_minimo = models.PositiveIntegerField(null=False)
    f_creado = models.DateTimeField(auto_now_add=True)
    categoria = models.ForeignKey(Categoria, on_delete=models.SET_NULL, null=True)


    def __str__(self):
        return self.nombre


class Precio(models.Model):
    cantidad = models.PositiveIntegerField(null=True, blank=True) 
    precio_uni = models.PositiveIntegerField(null=True, blank=True)
    precio_total = models.PositiveIntegerField(null=True, blank=True)
    f_actualizado = models.DateTimeField(auto_now=True)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE, blank=True)

    def save(self, *args, **kwargs):
        # Calcular el precio total antes de guardar
        self.precio_total = self.cantidad * self.precio_uni
        super(Precio, self).save(*args, **kwargs)

    def __str__(self):
        return self.producto.nombre
    

productos/forms.py
from django import forms
from .models import *
#from django_select2.forms import ModelSelect2Widget
# Formularios

class CrearProductoform(forms.ModelForm):
    categoria = forms.ModelChoiceField( # Obtener los registros nombres
        queryset = Categoria.objects.all(),
        empty_label = "Seleccionar categoria",
        widget = forms.Select(attrs={'class': 'form-control'})
    )
    class Meta:
        model = Producto
        fields = [
            'nombre',
            'categoria',
            'stock_minimo',
            'descripcion',
        ]
        labels = {
            'nombre': 'Nombre de producto',
            'stock_minimo': 'Stock minimo',
            'descripcion': 'Observacion',
        }
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese el producto'}),
            'stock_minimo': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese el minimo de stock'}),
            'descripcion' : forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Alguna observacion del producto'}),
        }

class CrearCategoria(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = [
            'nombre',
            'descripcion',
        ]
        labels = {'descripcion': 'Observacion'}
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese el nombre'}),
            'descripcion': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Ingrese el nombre'})
        }


class Compraproducto(forms.ModelForm):
    class Meta:
        model = Precio
        fields = [
            'producto',
            'cantidad', 
            'precio_uni',
        ]
        labels = {
            'producto': 'Nombre de producto',
            'cantidad': 'Cantidad de producto',
            'precio_uni': 'Precio por unidad',
        }
        widgets = {
            'producto': forms.Select(attrs={'class': 'form-control'}),
            'cantidad': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese cantidad comprada'}),
            'precio_uni': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese precio por uinidad'}),
        }


        def clean(self):
            cleaned_data = super().clean()
            cantidad = cleaned_data.get('cantidad')
            precio_uni = cleaned_data.get('precio_uni')
            if cantidad and precio_uni:
                cleaned_data['precio_total'] = cantidad * precio_uni
            return cleaned_data

productos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import *
# Create your views here.

def main(request):
    return render(request, 'main.html')


def crearproducto(request):
    if request.method == 'POST':
        form = CrearProductoform(request.POST)
        if form.is_valid():
            form.save()
            return redirect('main')
        else:
            return render(request, 'crearproducto.html', {
                'form': form,
                'error': 'Datos ingresados no son validos'
            })
    else:
        form = CrearProductoform()
        return render(request, 'crearproducto.html', {
            'form': form,
        })

def crearcategoria(request):
    if request.method == 'POST':
        form = CrearCategoria(request.POST)
        if form.is_valid():
            form.save()
            return redirect('main')
        else:
            return render(render, 'crearcategoria.html', {
                'form': form,
                'error': 'Los datos ingresados no son validos'
            })
    else:
        form = CrearCategoria(request.POST)
        return render(request, 'crearcategoria.html', {
            'form': form
        })

def crearcompra(request):
    if request.method == 'POST':
        form = Compraproducto(request.POST)
        if form.is_valid():
            form.save()
            return redirect('main')
        else:
            return render(request, 'c_producto.html', {
                'form': form,
                'error': 'Los datos ingresados no son validos'
            })
    else:
        form = Compraproducto(request.POST)
        return render(request, 'c_producto.html', {
            'form': form,
        })
    
def listar_producto(request):
    productos = Producto.objects.all()
    return render(request, 'listar_productos.html', {
        'productos': productos
    })

def eliminar_producto(request, producto_id):
    if request.method == 'POST':
        producto = get_object_or_404(Producto, pk=producto_id)
        producto.delete()
        return redirect('listarproducto')

def eliminar_categoria(request, categoria_id):
    if request.method == 'POST':
        categoria = get_object_or_404(Categoria, pk=categoria_id)
        categoria.delete()
        return redirect('listarcategoria')

def modificar_producto(request, producto_id):
    pass
        

def listar_categoria(request):
    categorias = Categoria.objects.all()
    return render(request, 'listar_categoria.html', {
        'categorias': categorias
    })

productos/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <title>Gestion de inventario</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="#">Gestion de inventario</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ms-auto">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'main' %}">Inicio</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                 Categoria
                </a>
                <ul class="dropdown-menu text-white-50" aria-labelledby="navbarDropdownMenuLink">
                  <li><a class="dropdown-item" href="{% url 'crearcategoria' %}">Dar de alta</a></li>
                  <li><a class="dropdown-item" href="{% url 'listarcategoria' %}">Listar categorias</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                 Repuesto
                </a>
                <ul class="dropdown-menu text-white-50" aria-labelledby="navbarDropdownMenuLink">
                  <li><a class="dropdown-item" href="{% url 'crearproducto' %}">Registrar repuesto</a></li>
                  <li><a class="dropdown-item" href="{% url 'compra' %}">Compra de repuesto</a></li>
                  <li><a class="dropdown-item" href="{% url 'listarproducto' %}">Listar repuesto</a></li>
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    {% block content %}
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script>
      $(document).ready(function() {
        $('#id_producto').select2();
      });
    </script>
</body>
</html>

productos/templates/c_producto.html
{% extends 'base.html' %}

{% block content %}
<main class="conteiner">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <form class="card card-body mt-4" method="POST">
                <h1 class="text-center mb-4">Registrar compra</h1> 
                {{error}}
                {% csrf_token %}
                {{ form.as_p}}
                <button class="btn btn-primary">
                    Guardar
                </button>
            </form>
        </div>
    </div>
</main> 
{% endblock %}

productos/templates/crearcategoria.html
{% extends 'base.html' %}

{% block content %}
<main class="conteiner">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <form class="card card-body mt-4" method="POST">
                <h1 class="text-center mb-4">Registrar producto</h1> 
                {{error}}
                {% csrf_token %}
                {{ form.as_p}}
                <button class="btn btn-primary">
                    Guardar
                </button>
            </form>
        </div>
    </div>
</main> 
{% endblock %}

productos/templates/crearproducto.html
{% extends 'base.html' %}

{% block content %}
<main class="conteiner">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <form class="card card-body mt-4" method="POST">
                <h1 class="text-center mb-4">Registrar producto</h1> 
                {{error}}
                {% csrf_token %}
                {{ form.as_p}}
                <button class="btn btn-primary">
                    Guardar
                </button>
            </form>
        </div>
    </div>
</main> 
{% endblock %}

productos/templates/listar_categoria.html
{% extends 'base.html' %}

{% block content %}
<main class="conteiner">
    <h1 class="text-center mt-4 mb-4 display-5">Lista de categoria</h1>
    <div class="table-responsive w-75 mx-auto">
        <table class="table">
            <thead>
              <tr>
                <th scope="col">Id</th>
                <th scope="col">Nombre</th>
                <th scope="col">Descripcion</th>
                <th></th>
              </tr>
            </thead>
            {% for categoria in categorias %}
            <tbody>
              <tr>
                <th scope="row">{{ categoria.id }}</th>
                <td>{{ categoria.nombre }}</td>
                <td>{{ categoria.descripcion }}</td> 
                <td>
                  <form action="{% url 'eliminarcategoria' categoria.id %}" method="POST" style="display:inline;">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger btn-sm">Eliminar</button>
                  </form>
                    <a href="" class="btn btn-primary btn-sm">
                        Modificar
                    </a>
                </td>
              </tr>
            </tbody>
            {% endfor %}
          </table>
    </div>
</main>
{% endblock %}

productos/templates/listar_productos.html
{% extends 'base.html' %}

{% block content %}
<main class="conteiner">
    <h1 class="text-center mt-4 mb-4 display-5">Lista de productos</h1>
    <div class="table-responsive w-75 mx-auto">
        <table class="table">
            <thead>
              <tr>
                <th scope="col">Id</th>
                <th scope="col">Nombre</th>
                <th scope="col">Descripcion</th>
                <th scope="col">Stock Actual</th>
                <th scope="col">Stock Minimo</th>
                <th scope="col">Categoria</th>
                <th scope="col">Fecha de creacion</th>
                <th></th>
              </tr>
            </thead>
            {% for producto in productos %}
            <tbody>
              <tr>
                <th scope="row">{{ producto.id }}</th>
                <td>{{ producto.nombre }}</td>
                <td>{{ producto.descripcion }}</td>
                <td>{{ producto.stock_actual }}</td>
                <td>{{ producto.stock_minimo }}</td>
                <td>{{ producto.categoria }}</td>
                <td>{{ producto.f_creado }}</td>
                <td>
                    <a href="{% url 'eliminarproducto' producto.id %}" class="btn btn-danger btn-sm">
                        Eliminar
                    </a>
                    <a href="" class="btn btn-primary btn-sm">
                        Modificar
                    </a>
                </td>
              </tr>
            </tbody>
            {% endfor %}
          </table>
    </div>
</main>
{% endblock %}

productos/templates/main.html
{% extends 'base.html' %}

{% block content %}
<main class="conteiner-5">
    <section class="card card-body">
        <h1 class="text-center display-1">Inicio</h1>
    </section>
</main>
{% endblock %}